# This is a basic workflow to help you get started with Actions

name: Update Website

# Controls when the workflow will run
on: push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run SSH command
        uses: garygrossgarten/github-action-ssh@v0.6.3
        with:
          command: /home/turing/z1929228/public_html/csci466/group_project/github/NIU-SP22-CSCI466-GroupProject/update.sh
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
